[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"

# [bans]
# multiple-versions = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[sources.allow-org]
github = ["narrowlink"]

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
copyleft = "deny"
confidence-threshold = 0.93
allow = ["MPL-2.0"]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
