.\" Manpage for Narrowlink Gateway.
.\" Contact support@narrowlink.io to correct errors or typos.
.TH NARROWLINK 1 "13 October 2023" "1.0" "Narrowlink Gateway man page"
.SH NAME
narrowlink \- Narrowlink Gateway command line utility
.SH SYNOPSIS
.B narrowlink
[options]
.SH DESCRIPTION
.B Narrowlink Gateway
is a command line utility for managing and configuring the Narrowlink Gateway.
.SH OPTIONS
.TP
.B -c, --config=
Specify a config file.
.TP
.B -h, --help
Print help information.
.TP
.B --version
Print version information.
.SH SEE ALSO
Additional documentation for
.B Narrowlink Gateway
is available at https://narrowlink.io/documentation
.SH AUTHOR
This manpage was written by the Narrowlink development team.

