.\" Manpage for Narrowlink Token Generator.
.\" Contact support@narrowlink.com to correct errors or typos.
.so .vars.roff
.TH NARROWLINK-TOKEN-GENERATOR 1 "23 October 2023" "\*(vN" "Narrowlink Token Generator man page"
.SH NAME
narrowlink-token-generator \- Narrowlink Token Generator command line utility
.SH SYNOPSIS
.B narrowlink-token-generator
[options]
.SH DESCRIPTION
.B Narrowlink Token Generator
is a command line utility for generating tokens.
.SH OPTIONS
.TP
.B -c, --config=
Specify a config file.
.TP
.B -h, --help
Print help information.
.TP
.B --version
Print version information.
.SH "PRIORITY TO LOAD CONFIG FILE"
.IP 1.
Custom path using \fB-c\fR command
.IP 2.
Current directory \fB./\fR
.IP 3.
Config directory + narrowlink:
.RS
.IP \[bu]
Linux: \fB/home/$USER/.config/narrowlink\fR
.IP \[bu]
macOS: \fB/Users/$USER/Library/Application Support/narrowlink\fR
.IP \[bu]
Windows: \fBC:\\Users\\$USER\\AppData\\Roaming\\narrowlink\fR
.RE
.IP 4.
Home directory + .narrowlink:
.RS
.IP \[bu]
Linux and macOS: \fB/home/$USER/.narrowlink\fR
.IP \[bu]
Windows: \fBC:\\Users\\$USER\\.narrowlink\fR
.RE
.IP 5.
\fB/etc/narrowlink\fR
.SH SEE ALSO
Additional documentation for
.B Narrowlink Token Generator
is available at https://narrowlink.com/docs/token-generator
.SH AUTHOR
This manpage was written by the Narrowlink development team.

