.\" Define version number
.ds vN 0.2.0-git-1697976735 
.\" Manpage for Narrowlink Gateway.
.\" Contact support@narrowlink.io to correct errors or typos.
.TH NARROWLINK-GATEWAY 1 "13 October 2023" "\*(vN" "Narrowlink Gateway man page"
.SH NAME
narrowlink-gateway \- Narrowlink Gateway command line utility
.SH SYNOPSIS
.B narrowlink-gateway
[options]
.SH DESCRIPTION
.B Narrowlink Gateway
is a command line utility for managing and configuring the Narrowlink Gateway.
.SH OPTIONS
.TP
.B -c, --config=
Specify a config file.
.TP
.B -h, --help
Print help information.
.TP
.B --version
Print version information.
.SH SEE ALSO
Additional documentation for
.B Narrowlink Gateway
is available at https://narrowlink.com/docs/intro
.SH AUTHOR
This manpage was written by the Narrowlink development team.

