.\" Manpage for command.
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 8 "06 May 2010" "1.0" "command man page"
.SH NAME
command \- explanation of the command.
.SH SYNOPSIS
.B command
[-abc] [-d | -e] filename
.SH DESCRIPTION
.B command
is a utility for ...
.SH OPTIONS
.TP
.B \-a
Does this.
.TP
.B \-b
Does that.
.TP
.B \-c
Does something else.
.SH SEE ALSO
other_command(1)
.SH AUTHOR
This manpage was written by Username.

