name: Deny

on:
  pull_request:
    paths:
      - '**/Cargo.toml'
  push:
    paths:
      - '**/Cargo.toml'
# env:
#   CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v1
